Lesson 17
GiannaGrale/SauceDemo_PageObject pull request #8
Opened 2021-08-13 10:23 UTC by GiannaGrale

2021-08-23 09:32 UTC, wildpioneer requested changes

2021-08-23 09:32 UTC, wildpioneer commented on src/main/java/baseEntities/BaseTest.java
> +    @BeforeSuite
У тебя 2 BeforeSuite метода - это так надо или ты просто забыла их объединить?

2021-08-23 09:32 UTC, wildpioneer commented on src/test/java/tests/api/TestRailApiTest.java
> +        String endpoint ="index.php?/api/v2/get_projects";
Вынести эндпоинты в отдельный класс - который уже есть

2021-08-23 09:32 UTC, wildpioneer commented on src/test/java/tests/api/ApiReqresTest.java
> +public class ApiReqresTest {
Тут тоже можно было сделать отдельный базовый класс - потому как у тебя в каждом тесте много повторяющихся действий

2021-08-23 09:32 UTC, wildpioneer commented on src/test/java/tests/api/ApiReqresTest.java
> +        httpRequest.body("{\n" +
Лучше параметризировать JSON - через String.Formater

2021-08-24 11:35 UTC, GiannaGrale commented on src/test/java/tests/api/ApiReqresTest.java
> +        httpRequest.body("{\n" +
сделала

2021-08-24 11:35 UTC, GiannaGrale commented on src/test/java/tests/api/ApiReqresTest.java
> +public class ApiReqresTest {
вынесла в базовый класс

2021-08-24 11:35 UTC, GiannaGrale commented on src/test/java/tests/api/TestRailApiTest.java
> +        String endpoint ="index.php?/api/v2/get_projects";
вынесла эндпоинты

2021-08-24 11:36 UTC, GiannaGrale commented on src/main/java/baseEntities/BaseTest.java
> +    @BeforeSuite
здесь 1 для билдера, 2-ой для для value of objects. разнесла их по разным классам

2021-09-26 15:22 UTC, closed without merging